language: python
python:
  - "2.7"
  - "3.5"
cache:
  apt: true
  directories:
    - $HOME/.cache/pip
addons:
  apt:
    packages:
      - libatlas3gf-base
      - libatlas-dev
      - liblapack-dev
before_install:
  - pip install -U pip setuptools wheel
install:
  - pip install .
  - pip install xgboost
  - python -m nltk.downloader stopwords
script:
  - python simple_test.py
  - travis_wait 30 python examples/imdb_eval.py
  - travis_wait 30 python examples/tink_eval.py
  - travis_wait 30 python examples/job_eval.py
#  - for script in ./benchmark/*.sh; do $script; done
